// <auto-generated />
using CookBook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookBook.Migrations
{
    [DbContext(typeof(CookBookContext))]
    partial class CookBookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CookBook.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nom_categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("CookBook.Models.Etapes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_recette")
                        .HasColumnType("int");

                    b.Property<int>("RecetteId")
                        .HasColumnType("int");

                    b.Property<string>("description_etape")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("titre_etape")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecetteId");

                    b.ToTable("Etapes");
                });

            modelBuilder.Entity("CookBook.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nom_ingredient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("CookBook.Models.Recette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("description_recette")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo_recette")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titre_recette")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("utilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("utilisateurId");

                    b.ToTable("Recette");
                });

            modelBuilder.Entity("CookBook.Models.RecetteIngredient", b =>
                {
                    b.Property<int>("recetteId")
                        .HasColumnType("int");

                    b.Property<int>("ingredientId")
                        .HasColumnType("int");

                    b.Property<string>("quantite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("recetteId", "ingredientId");

                    b.HasIndex("ingredientId");

                    b.ToTable("RecetteIngredients");
                });

            modelBuilder.Entity("CookBook.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nom_role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("CookBook.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("RecetteUtilisateur", b =>
                {
                    b.Property<int>("RecettesFavorisId")
                        .HasColumnType("int");

                    b.Property<int>("utilisateursFavorisId")
                        .HasColumnType("int");

                    b.HasKey("RecettesFavorisId", "utilisateursFavorisId");

                    b.HasIndex("utilisateursFavorisId");

                    b.ToTable("RecetteUtilisateur");
                });

            modelBuilder.Entity("CookBook.Models.Etapes", b =>
                {
                    b.HasOne("CookBook.Models.Recette", "Recette")
                        .WithMany("etapes")
                        .HasForeignKey("RecetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recette");
                });

            modelBuilder.Entity("CookBook.Models.Recette", b =>
                {
                    b.HasOne("CookBook.Models.Categorie", "categorie")
                        .WithMany("Recettes")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookBook.Models.Utilisateur", "utilisateur")
                        .WithMany("RecettesCrees")
                        .HasForeignKey("utilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categorie");

                    b.Navigation("utilisateur");
                });

            modelBuilder.Entity("CookBook.Models.RecetteIngredient", b =>
                {
                    b.HasOne("CookBook.Models.Ingredient", "ingredient")
                        .WithMany("recetteIngredients")
                        .HasForeignKey("ingredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookBook.Models.Recette", "recette")
                        .WithMany("recetteIngredients")
                        .HasForeignKey("recetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ingredient");

                    b.Navigation("recette");
                });

            modelBuilder.Entity("CookBook.Models.Utilisateur", b =>
                {
                    b.HasOne("CookBook.Models.Role", "Role")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RecetteUtilisateur", b =>
                {
                    b.HasOne("CookBook.Models.Recette", null)
                        .WithMany()
                        .HasForeignKey("RecettesFavorisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookBook.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("utilisateursFavorisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CookBook.Models.Categorie", b =>
                {
                    b.Navigation("Recettes");
                });

            modelBuilder.Entity("CookBook.Models.Ingredient", b =>
                {
                    b.Navigation("recetteIngredients");
                });

            modelBuilder.Entity("CookBook.Models.Recette", b =>
                {
                    b.Navigation("etapes");

                    b.Navigation("recetteIngredients");
                });

            modelBuilder.Entity("CookBook.Models.Role", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("CookBook.Models.Utilisateur", b =>
                {
                    b.Navigation("RecettesCrees");
                });
#pragma warning restore 612, 618
        }
    }
}
